# Blckswan Security
#
# Hardended security-API with features from the  Blckswan-2.0 specification
#
# OpenAPI spec version: 3.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' ErrorModel Class
#'
#' @field code 
#' @field message 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ErrorModel <- R6::R6Class(
  'ErrorModel',
  public = list(
    `code` = NULL,
    `message` = NULL,
    initialize = function(`code`, `message`){
      if (!missing(`code`)) {
        stopifnot(is.numeric(`code`), length(`code`) == 1)
        self$`code` <- `code`
      }
      if (!missing(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
    },
    toJSON = function() {
      ErrorModelObject <- list()
      if (!is.null(self$`code`)) {
        ErrorModelObject[['code']] <- self$`code`
      }
      if (!is.null(self$`message`)) {
        ErrorModelObject[['message']] <- self$`message`
      }

      ErrorModelObject
    },
    fromJSON = function(ErrorModelJson) {
      ErrorModelObject <- jsonlite::fromJSON(ErrorModelJson)
      if (!is.null(ErrorModelObject$`code`)) {
        self$`code` <- ErrorModelObject$`code`
      }
      if (!is.null(ErrorModelObject$`message`)) {
        self$`message` <- ErrorModelObject$`message`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "code": %d,
           "message": %s
        }',
        self$`code`,
        self$`message`
      )
    },
    fromJSONString = function(ErrorModelJson) {
      ErrorModelObject <- jsonlite::fromJSON(ErrorModelJson)
      self$`code` <- ErrorModelObject$`code`
      self$`message` <- ErrorModelObject$`message`
    }
  )
)
