# Blckswan Security
#
# Hardended security-API with features from the  Blckswan-2.0 specification
#
# OpenAPI spec version: 3.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' Loc Class
#'
#' @field name 
#' @field tag 
#' @field id 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Loc <- R6::R6Class(
  'Loc',
  public = list(
    `name` = NULL,
    `tag` = NULL,
    `id` = NULL,
    initialize = function(`name`, `tag`, `id`){
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`tag`)) {
        stopifnot(is.character(`tag`), length(`tag`) == 1)
        self$`tag` <- `tag`
      }
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
    },
    toJSON = function() {
      LocObject <- list()
      if (!is.null(self$`name`)) {
        LocObject[['name']] <- self$`name`
      }
      if (!is.null(self$`tag`)) {
        LocObject[['tag']] <- self$`tag`
      }
      if (!is.null(self$`id`)) {
        LocObject[['id']] <- self$`id`
      }

      LocObject
    },
    fromJSON = function(LocJson) {
      LocObject <- jsonlite::fromJSON(LocJson)
      if (!is.null(LocObject$`name`)) {
        self$`name` <- LocObject$`name`
      }
      if (!is.null(LocObject$`tag`)) {
        self$`tag` <- LocObject$`tag`
      }
      if (!is.null(LocObject$`id`)) {
        self$`id` <- LocObject$`id`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s,
           "tag": %s,
           "id": %d
        }',
        self$`name`,
        self$`tag`,
        self$`id`
      )
    },
    fromJSONString = function(LocJson) {
      LocObject <- jsonlite::fromJSON(LocJson)
      self$`name` <- LocObject$`name`
      self$`tag` <- LocObject$`tag`
      self$`id` <- LocObject$`id`
    }
  )
)
